CREATE USER '$MARIADB_DB1_USER'@'%' IDENTIFIED BY '$MARIADB_DB1_PASS';

CREATE DATABASE IF NOT EXISTS `$MARIADB_DB1_NAME` COLLATE 'utf8mb4_unicode_ci';
GRANT ALL ON $MARIADB_DB1_NAME.* TO '$MARIADB_DB1_USER'@'%';

FLUSH PRIVILEGES;