#!/env/bash

mydomains=$(echo "SELECT domain FROM domains" | mysql $TRAEFIK_MARIADB_DOMAINS_DB -u $TRAEFIK_MARIADB_DOMAINS_USER -p$TRAEFIK_MARIADB_DOMAINS_USER)
mysubdomains=$(echo "SELECT domain FROM domains" | mysql $TRAEFIK_MARIADB_DOMAINS_DB -u $TRAEFIK_MARIADB_DOMAINS_USER -p$TRAEFIK_MARIADB_DOMAINS_USER)
