api:
    dashboard: true
    insecure: true

entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

providers:
    docker:
        exposedByDefault: false
        swarmMode: false
        watch: true
    file:
        directory: /file-providers
        watch: true

log:
  level: debug
  filePath: "/var/log/traefik/traefik.log"

accessLog:
    filePath: "/var/log/traefik/access.log"
    bufferingSize: 100

certificatesResolvers:
    letsencrypt:
        acme:
          caServer: https://acme-v02.api.letsencrypt.org/directory
          email: admin@onlineacademy.ir
          storage: /letsencrypt/acme.json
          httpChallenge:
              entryPoint: web
